### ISSUE TITLE
Discussion: natural language API

### ISSUE THREAD

**Issue by floofytobles** [floofytobles/procedural-text-adventure#4]
Steph (she's new, joined earlier this evening- not for lack of trying, Discord links kept expiring) brought up the possibility of using a natural language API. I've also been working on a Language & Actions spreadsheet to try to get together some of the world interaction mechanics.

Thoughts?

**Comment by jmdejong** [comment]
It could be interesting, but it could also be overkill for this project.

Could you give some examples of natural language API's? That may give a better idea what they can do.

Do you also know any games that use proper natural language parsing? How does it enhance gameplay?

**Comment by floofytobles** [comment]
Decided in the Discord that we will likely not use a natural language API.
